### ISSUE TITLE
Adaptive Accents doesn't enable

### ISSUE THREAD

**Issue by Ravioliii** [Amaru8/Cider-AdaptiveAccentsEverywhere#3]
Not sure if this is a Cider issue or a plugin issue but I'm not able to turn on the plugin after downloading it. At one point it did work, but then it stopped sometime last week. 
![Screenshot 2024-12-01 140240](https://github.com/user-attachments/assets/7e21420c-9be6-45b1-be24-c94586c774cd)

Pressing the enable button doesn't work. The plugin is fully updated to 1.1.1 and I'm using the newest build of Cider from the Taproom Releases The plugin hasn't worked on the last two updates if I'm not mistaken.

**Comment by Amaru8** [comment]
Hey~ What is your platform?

**Comment by Ravioliii** [comment]
I'm on Windows 24H2

**Comment by Amaru8** [comment]
Are you using a build from the Experimental category in Taproom?

**Comment by Ravioliii** [comment]
Yes, I've been using the most recent experimental builds from Taproom whenever they come out

**Comment by Amaru8** [comment]
Please try the plugin with a build from the Stable category on Taproom and check if you can still reproduce the issue.

**Comment by Ravioliii** [comment]
Works on the stable client and when updating to use ptb 76 it works as well.

**Comment by Amaru8** [comment]
Thanks for the info. I am working on a fix for experimental builds.

**Comment by Amaru8** [comment]
Fixed in 1.1.2, available on Marketplace.

**Comment by Ravioliii** [comment]
Unfortunate issue. I can enable the plugin now but it's not active and working. 2.6.0. PTB 97 and previous as well as 2.6.0.5 and 2.6.0.8 don't work.

**Comment by Amaru8** [comment]
Please verify you are using the latest version of my plugin (1.1.2), and if you are, please forward your exact setup (base and spa version), so I have something I can test with. My primary focus is that the plugin works on the latest stable version, whether it works on PTBs and Experimental builds are just a side-effect.

**Comment by Amaru8** [comment]
Please open a new issue tho, as they seem separated. I myself got confused too, the fix in 1.1.2 was a functionality fix, or I thought I fixed it. The plugin not getting enabled was resolved by Core in the Cider codebase iirc.
